language: python

sudo: false
cache:
  apt: true
  directories:
    - $HOME/.pip-cache/

addons:
  apt:
    packages:
      - expect-dev
      - python-lxml
      - python-simplejson
      - python-yaml

python:
  - "2.7"

virtualenv:
  system_site_packages: true

env:
  global:
  - TEST_OTHER_PROJECTS=${HOME}/addons-vauxoo LINT_CHECK=0 TESTS="0" VERSION="8.0"
  - secure: "S46yHEhBgGef0Y3aR18yH4tzp97xgZ+pChsa+R+sgpV3o58YB99SbBPau+2cmssSWA4OlcsCam8nvb6lmQGWjys0kiu+j627ugVwvWuLGXq4Nt216VGz48kweb8/Y9qpHxFXuWBp2cw/QhpJaasnhRNSfNaCZg/LdelZAzEj3MU="

  matrix:
  - LINT_CHECK=1
  - TESTS="1" ODOO_REPO="odoo/odoo"
  - TESTS="1" ODOO_REPO="vauxoo/odoo"
  - TRANSIFEX="1" INCLUDE=""

install:
  - git clone --single-branch --depth=1 https://github.com/vauxoo/maintainer-quality-tools.git -b master ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly
  - pip install beautifulsoup4

script:
  - travis_wait travis_run_tests

after_success:
  - travis_after_tests_success
